apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clinique
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Khaoulachaouaty/SpringBootDevops.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true   # k8s/ contains subfolders (backend/, frontend/, mysql/, monitoring/)
      exclude: '{argocd/*,create-secrets.sh}'  # don't try to apply ArgoCD app to itself or shell script

  destination:
    server: https://kubernetes.default.svc
    namespace: clinique

  syncPolicy:
    automated:
      prune: true       # remove resources deleted from git
      selfHeal: true    # revert manual kubectl changes
    syncOptions:
      - CreateNamespace=true
